version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: edustack_postgres
    environment:
      POSTGRES_DB: edustack
      POSTGRES_USER: edustack
      POSTGRES_PASSWORD: edustack123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - edustack_network

  redis:
    image: redis:7-alpine
    container_name: edustack_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - edustack_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: edustack_backend
    environment:
      DATABASE_URL: postgresql://edustack:edustack123@postgres:5432/edustack
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - edustack_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  edustack_network:
    driver: bridge
